import './globals.css'

import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic'
import { draftMode } from 'next/headers'
import { token } from '@/utils/sanity/fetch'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })
const PreviewProvider = dynamic(() => import('@/components/PreviewProvider'))

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  draftMode().enable()
  return (
    <html lang="en">
      <body className={inter.className}>
        {draftMode().isEnabled ? (
          <PreviewProvider token={token}>{children}</PreviewProvider>
        ) : (
          children
        )}
      </body>
    </html>
  )
}
