import '@/styles/globals.css'

import dynamic from 'next/dynamic'
import { draftMode } from 'next/headers'
import { env } from '@/utils/env'
import type { Metadata } from 'next'

const PreviewProvider = dynamic(() => import('@/components/PreviewProvider'))

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { isEnabled } = draftMode()

  return (
    <html lang="en">
      <body>
        {isEnabled ? (
          <PreviewProvider token={env.sanity.token}>{children}</PreviewProvider>
        ) : (
          children
        )}
      </body>
    </html>
  )
}
